src/Entity/Doctor.php
<?php

namespace App\Entity;

use App\Repository\DoctorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DoctorRepository::class)]
class Doctor
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::ARRAY, nullable: true)]
    private array $unavailable_days = [];

    #[ORM\Column(nullable: true)]
    private ?int $total_points = null;

    #[ORM\OneToMany(mappedBy: 'doctor', targetEntity: Shift::class)]
    private Collection $shifts;

    public function __construct()
    {
        $this->shifts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getUnavailableDays(): array
    {
        return $this->unavailable_days;
    }

    public function setUnavailableDays(?array $unavailable_days): static
    {
        $this->unavailable_days = $unavailable_days;

        return $this;
    }

    public function getTotalPoints(): ?int
    {
        return $this->total_points;
    }

    public function setTotalPoints(?int $total_points): static
    {
        $this->total_points = $total_points;

        return $this;
    }

    /**
     * @return Collection<int, Shift>
     */
    public function getShifts(): Collection
    {
        return $this->shifts;
    }

    public function addShift(Shift $shift): static
    {
        if (!$this->shifts->contains($shift)) {
            $this->shifts->add($shift);
            $shift->setDoctor($this);
        }

        return $this;
    }

    public function removeShift(Shift $shift): static
    {
        if ($this->shifts->removeElement($shift)) {
            // set the owning side to null (unless already changed)
            if ($shift->getDoctor() === $this) {
                $shift->setDoctor(null);
            }
        }

        return $this;
    }
}

src/Form/DoctorType.php
<?php

namespace App\Form;

use App\Entity\Day;
use App\Entity\Doctor;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DoctorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class)
            ->add('unavailable_days', CollectionType::class, [
                'entry_type' => EntityType::class,
                'entry_options' => [
                    'class' => Day::class,
                    'choice_label' => 'date',
                    'multiple' => true,
                    'expanded' => true,
                ],
            ])
            ->add('total_points')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Doctor::class,
        ]);
    }
}

src/Controller/DoctorController.php
<?php

namespace App\Controller;

use App\Entity\Doctor;
use App\Form\DoctorType;
use App\Repository\DoctorRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/doctor')]
class DoctorController extends AbstractController
{
    #[Route('/', name: 'app_doctor_index', methods: ['GET'])]
    public function index(DoctorRepository $doctorRepository): Response
    {
        return $this->render('doctor/index.html.twig', [
            'doctors' => $doctorRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_doctor_new', methods: ['GET', 'POST'])]
    public function new(Request $request, DoctorRepository $doctorRepository): Response
    {
        $doctor = new Doctor();
        $form = $this->createForm(DoctorType::class, $doctor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $doctorRepository->save($doctor, true);

            return $this->redirectToRoute('app_doctor_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('doctor/new.html.twig', [
            'doctor' => $doctor,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_doctor_show', methods: ['GET'])]
    public function show(Doctor $doctor): Response
    {
        return $this->render('doctor/show.html.twig', [
            'doctor' => $doctor,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_doctor_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Doctor $doctor, DoctorRepository $doctorRepository): Response
    {
        $form = $this->createForm(DoctorType::class, $doctor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $doctorRepository->save($doctor, true);

            return $this->redirectToRoute('app_doctor_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('doctor/edit.html.twig', [
            'doctor' => $doctor,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_doctor_delete', methods: ['POST'])]
    public function delete(Request $request, Doctor $doctor, DoctorRepository $doctorRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$doctor->getId(), $request->request->get('_token'))) {
            $doctorRepository->remove($doctor, true);
        }

        return $this->redirectToRoute('app_doctor_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/doctor/_delete_form.html.twig
<form method="post" action="{{ path('app_doctor_delete', {'id': doctor.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ doctor.id) }}">
    <button class="btn">Delete</button>
</form>

templates/doctor/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/doctor/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Doctor{% endblock %}

{% block body %}
    <h1>Edit Doctor</h1>

    {{ include('doctor/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_doctor_index') }}">back to list</a>

    {{ include('doctor/_delete_form.html.twig') }}
{% endblock %}

templates/doctor/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Doctor index{% endblock %}

{% block body %}
    <h1>Doctor index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Unavailable_days</th>
                <th>Total_points</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for doctor in doctors %}
            <tr>
                <td>{{ doctor.id }}</td>
                <td>{{ doctor.name }}</td>
                <td>{{ doctor.unavailableDays ? doctor.unavailableDays|join(', ') : '' }}</td>
                <td>{{ doctor.totalPoints }}</td>
                <td>
                    <a href="{{ path('app_doctor_show', {'id': doctor.id}) }}">show</a>
                    <a href="{{ path('app_doctor_edit', {'id': doctor.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_doctor_new') }}">Create new</a>
{% endblock %}

templates/doctor/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Doctor{% endblock %}

{% block body %}
    <h1>Create new Doctor</h1>

    {{ include('doctor/_form.html.twig') }}

    <a href="{{ path('app_doctor_index') }}">back to list</a>
{% endblock %}

templates/doctor/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Doctor{% endblock %}

{% block body %}
    <h1>Doctor</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ doctor.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ doctor.name }}</td>
            </tr>
            <tr>
                <th>Unavailable_days</th>
                <td>{{ doctor.unavailableDays ? doctor.unavailableDays|join(', ') : '' }}</td>
            </tr>
            <tr>
                <th>Total_points</th>
                <td>{{ doctor.totalPoints }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_doctor_index') }}">back to list</a>

    <a href="{{ path('app_doctor_edit', {'id': doctor.id}) }}">edit</a>

    {{ include('doctor/_delete_form.html.twig') }}
{% endblock %}